### ISSUE TITLE
ubuntu 14.04 成功安装

### ISSUE THREAD

**Issue by VaneHay** [yuan1994/wechat_web_devtools#1]
ubuntu 14.04 成功安装,第一次运行.提示最新版本 0.10.102800

哈哈哈  多谢

**Comment by yuan1994** [comment]
@VaneHay 多谢支持，好用就帮忙分享一下。如果有什么问题在这里跟我反馈就行

**Comment by VaneHay** [comment]
@yuan1994 恩,分享了. 但是没破解,因为我没appid

**Comment by yuan1994** [comment]
@VaneHay 这个就是正版，本来就不需要破解，只是如果没有应用号无法使用小程序开发而已，不过微信网页开发功能比0.7.0也要好些了

**Comment by chengfangpeng** [comment]
怎么更新？

**Comment by yuan1994** [comment]
目前最新的两个版本都尝试过了，无法移植到Linux平台，小程序编辑那块出现bug，其他的都正常，不敢发布更新，你们也别更新，自己不加修改就更新会打不开的

**Comment by SakuraXs** [comment]
安装成功，可是打开提示，无法加载一下来源的扩展情况：.清单文件缺失或不可读    是怎么回事

**Comment by yuan1994** [comment]
已更新，感谢大家的支持，因做毕设忙得没心情更新了，耽误大家了，很抱歉
