### ISSUE TITLE
调用wcc路径问题

### ISSUE THREAD

**Issue by rexlevin** [yuan1994/wechat_web_devtools#10]
在使用中有个调用wcc的问题，始终会访问项目路径+home路径+wcc。
比如我的项目路径是：/depot/WebChatProject/demo
home下wcc路径是：/home/rexlevin/.config/微信web开发者工具/WeappVendor/wcc
最后报错信息是：Error: ENOENT: no such file or directory, open '/depot/WebChatProject/demo/home/rexlevin/.config/微信web开发者工具/WeappVendor/wcc'

另：哥们很快啊，我昨天才留意到tx更新的ide，还没下包看呢，你已经更新了。

**Comment by rexlevin** [comment]
还有这个版本tx用的是0.17.6，yuan你使用了0.19的nw，我不知道会不会有差异，可能最好还是使用同样版本的nw比较好。
建议以后可以只上传app、node_modules、package.json这个三个文件夹/文件，另外说明使用nw版本，这样上传文件就能大大减小。

**Comment by yuan1994** [comment]
回复message2：
你这个问题提得很好，那我以后弄两个分支，一个整合nwjs，一个只上传核心源码，很多人不知道这个开发工具是nwjs做的，所以如果拿到核心源码他们也不知道如何下手
tx用的哪个版本的nwjs如何看？我没注意到这个啊，我就一直用最新的nwjs

回复message1：
之前就打算更新版本的，但腾讯出了新版后，小程序编辑那里一直出现bug，打算放弃的，然后又要考试了，没心情敲代码，就又折腾起这个小工具了，然后知道如果解决编辑器出错的问题，就直接把文件拖过来了，很多地方就没在意系统识别的问题了，测试没发现问题就更新了，再不更新你们只能等到我考试完再更新咯，那时候小程序都正式上线了，哈哈

**Comment by rexlevin** [comment]
message1：这个运行文件路径的问题我暂时也没有时间去搞，工作上最近比较忙；你要是也没时间的话只有希望能有其他人来看看了。
message2：我个人的意见是就一个没有nwjs的版本行了，咱在readme里面讲述清楚就好，能用这个的如果搞不清楚nwjs的恐怕没有吧？！真要有那样的人看readme也应该能看懂，要是readme写清楚了都不能明白的话，还是不要搞开发最好了。
另：看nwjs的版本的话，对小程序ide的windows版，删掉package.nw再运行“微信web开发者工具.exe”就能看到。

**Comment by yuan1994** [comment]
已更新，感谢大家的支持，因做毕设忙得没心情更新了，耽误大家了，很抱歉
