### ISSUE TITLE
Ubuntu14.04无法打开

### ISSUE THREAD

**Issue by xubaifuCode** [yuan1994/wechat_web_devtools#12]
xu-cat@xu-cat:~$ /opt/tencent/wechat_web_devtools/nw
bash: /opt/tencent/wechat_web_devtools/nw: cannot execute binary file: 可执行文件格式错误

xu-cat@xu-cat:~$ sudo /opt/tencent/wechat_web_devtools/nw
/opt/tencent/wechat_web_devtools/nw: 1: /opt/tencent/wechat_web_devtools/nw: Syntax error: word unexpected (expecting ")")

Linux小白，以下两句都试过
sudo chown -R xu-cat.xu-cat /opt/tencent
sudo chown -R xu-cat /opt/tencent

**Comment by michico2000** [comment]
跟你一样的问题啊   怎么办呢？

**Comment by yuan1994** [comment]
已更新，感谢大家的支持，因做毕设忙得没心情更新了，耽误大家了，很抱歉
