### ISSUE TITLE
编译时找不到wxml文件？

### ISSUE THREAD

**Issue by lvchangqi** [yuan1994/wechat_web_devtools#14]
![2017-01-11 22-41-57](https://cloud.githubusercontent.com/assets/15379292/21852779/60c9a4e4-d84f-11e6-84db-03374eb0e1aa.png)

**Comment by lvchangqi** [comment]
![2017-01-12 11-16-40](https://cloud.githubusercontent.com/assets/15379292/21875688/cd4ad6ce-d8b8-11e6-982c-c693a5341183.png)

**Comment by yuan1994** [comment]
已更新，感谢大家的支持，因做毕设忙得没心情更新了，耽误大家了，很抱歉
