### ISSUE TITLE
Cannot read property 'webviewId' of undefined

### ISSUE THREAD

**Issue by luoziyihao** [yuan1994/wechat_web_devtools#15]
打开项目的时候就报这个错
![image](https://cloud.githubusercontent.com/assets/11476305/21927939/0cbce436-d9c3-11e6-9b94-6ba061ff1943.png)

**Comment by yuan1994** [comment]
已更新，感谢大家的支持，因做毕设忙得没心情更新了，耽误大家了，很抱歉
