### ISSUE TITLE
ubuntu16 启动提示错误，然后无法加载信息

### ISSUE THREAD

**Issue by jianliangWang** [yuan1994/wechat_web_devtools#16]
![screenshot from 2017-01-14 20-46-19](https://cloud.githubusercontent.com/assets/16470189/21955132/9d5a4cb8-da9f-11e6-9052-f4dae78b4de0.png)
![screenshot from 2017-01-14 21-23-22](https://cloud.githubusercontent.com/assets/16470189/21955134/b58dced6-da9f-11e6-8a23-ed57626252f6.png)

这是为什么呀，大神帮忙

**Comment by aoquan** [comment]
遇到了同样的问题

**Comment by kelln** [comment]
我也是诶

**Comment by lvchangqi** [comment]
似乎编译的时候需要一个exe文件。需要wine来支持

**Comment by kelln** [comment]
是的，楼上正解，需要wine才能跑起来，我用的16.04，混用了源，现在装不了wine，很多依赖问题解决不了，需要给一个包降级才可以。试了很久失败了，就转到win7下开发了。还有这个开发工具不兼容XP32位

**Comment by Topgt** [comment]
同上，有人解决了吗？

**Comment by yuan1994** [comment]
已更新，感谢大家的支持，因做毕设忙得没心情更新了，耽误大家了，很抱歉
