### ISSUE TITLE
如何更新微信的web开发者工具

### ISSUE THREAD

**Issue by wdrich** [yuan1994/wechat_web_devtools#17]
请问如何更新如何更新微信的web开发者工具 新版的工具修复了一些bug

**Comment by jerryzyz008** [comment]
如果作者不是很有时间更新的话可否把方法放出来让大家帮忙更新呢

**Comment by yuan1994** [comment]
已更新，感谢大家的支持，因做毕设忙得没心情更新了，耽误大家了，很抱歉
