### ISSUE TITLE
关于 Arch Linux AUR 打包的问题

### ISSUE THREAD

**Issue by BruceZhang1993** [yuan1994/wechat_web_devtools#22]
Arch Linux AUR: https://aur.archlinux.org/packages/wechat-web-devtools-git/

请问有详细的依赖列表吗，有的话我会更新这个 AUR 包的依赖项。

**Comment by yuan1994** [comment]
已更新，感谢大家的支持，因做毕设忙得没心情更新了，耽误大家了，很抱歉

**Comment by BruceZhang1993** [comment]
为了缩减软件包大小，AUR包切换到 core 分支并依赖 nwjs-bin
