### ISSUE TITLE
点了下更新，然后更新太慢了。不想更新关掉之后再也打不开了。。

### ISSUE THREAD

**Issue by super13** [yuan1994/wechat_web_devtools#39]
RT,找不到 控制是不是更新的文件在哪。。。重新安装也还是会更新。但是更新等了很久又没反应。。。

**Comment by Photokeep** [comment]
一样,希望给个指导

**Comment by super13** [comment]
找到了~/.config/有个 微信xxxxxx    原先搜weixin,wechat 没想到用的中文。。。
