### ISSUE TITLE
更新出错后重新clone一份还是继续显示更新

### ISSUE THREAD

**Issue by nisests** [yuan1994/wechat_web_devtools#4]
Ubuntu16.04，之前clone了一份，可以运行，但是我点了更新，然后看到issues里更新会出错的问题后，我删掉了原来的那份，重新clone一份后再次运行时直接显示在更新了

**Comment by yuan1994** [comment]
```
// 完全删除原来的安装包
sudo rm -rf /opt/tencent/wechat_web_devtools
// 删除配置项
sudo rm -rf ~/.config/微信web开发者工具
// 删除缓存
sudo rm -rf ~/.cache/微信web开发者工具
```
千万不要！千万不要！千万不要升级，不知道微信团队是故意不让Linux用还是代码写得有问题，反正我怎么改源码，最近出的两个版本都在微信小程序编辑那块出错，所以不敢发布，你们也别更新，想用还是先装虚拟机吧，或者和微信团队联系，看他们愿不愿意开发Linux版的

**Comment by nisests** [comment]
@yuan1994 这样是可以的，关闭后再打开就又变成更新了，每次运行前都要删一下吗

**Comment by Wszl** [comment]
mint 18 基于Ubuntu 16 LTS ，能正常使用，不过出现了这个更新问题，建议作者能不能把更新提示屏蔽掉？不然很容易更新后，然后需要重新安装

**Comment by yuan1994** [comment]
@nisests @Wszl 我已经屏蔽掉自动更新了，你们重新下载一下，我也是刚刚才发现微信给强制开启自动更新了，好坑啊，这是想尽一切办法干掉Linux平台呀

**Comment by yuan1994** [comment]
先删除之前的，包括缓存和配置项
```
// 完全删除原来的安装包
sudo rm -rf /opt/tencent/wechat_web_devtools
// 删除配置项
sudo rm -rf ~/.config/微信web开发者工具
// 删除缓存
sudo rm -rf ~/.cache/微信web开发者工具
```
然后再重新克隆就好了

**Comment by jerry79** [comment]
@Wszl 你好，我的也是mint18 但是预览无法使用，能帮我核对一下系统信息吗？我的如下图，谢谢
 
![image](https://cloud.githubusercontent.com/assets/2713806/20658932/4c4ce360-b57b-11e6-96f9-16e68eadd5e4.png)

**Comment by Wszl** [comment]
@jerry79 我的桌面环境是xfce 其他和你没有区别，你在终端环境运行一下，把错误代码发上来呗，我猜测是你没有装php

**Comment by yuan1994** [comment]
这个不需要装php，应该是有nodejs就行了，然后最好有nodejs的全局变量

**Comment by jerry79** [comment]
@Wszl 现在的错误是两条：
`[3614:3614:1129/162051:ERROR:desktop_window_tree_host_x11.cc(927)] Not implemented reached in virtual void views::DesktopWindowTreeHostX11::InitModalType(ui::ModalType)
[3614:3614:1129/162056:ERROR:browser_plugin_guest.cc(440)] Attempting to require callback on nonexistent surface
`
@yuan1994 请教如何设置node的全局变量，我是直接apt-get 安装的。
非常感谢！

**Comment by yuan1994** [comment]
先下载好nodejs，去官网下载LTS版，然后解压
```
// 解压
tar -zxvf node*文件名.tar.gz
// 修改可执行文件权限
sudo chmod a+x node*文件夹名/bin/*
// 移动到系统里
sudo mv node*文件夹名 /usr/local/node
// 设置全局变量
sudo echo 'export PATH=/usr/local/node/bin:\$PATH' > /etc/profile
// 使全局变量生效
source /etc/profile
```
还有问题就问搜索引擎吧，先把你用apt-get安装的给卸载了

**Comment by jerry79** [comment]
@yuan1994 非常感谢，我看了一下系统，之前就已经设置好了，如图，所以应该不是这个问题，唉，愁人。
![image](https://cloud.githubusercontent.com/assets/2713806/20735853/ccddfa4c-b6dd-11e6-96c7-97bfd538229d.png)

**Comment by Wszl** [comment]
@jerry79 看错误信息大概是桌面环境没有应用所需的部分实现，我和你的差别就在于桌面环境，我的是xfce4，你或许可以试一下

**Comment by jerry79** [comment]
@Wszl 谢谢，有时间再试试吧，现在先用虚拟机凑合一下。

**Comment by yuan1994** [comment]
已更新，感谢大家的支持，因做毕设忙得没心情更新了，耽误大家了，很抱歉
