### ISSUE TITLE
Ubuntu16.04版本 创建项目之后加载不出用户信息

### ISSUE THREAD

**Issue by 571618587** [yuan1994/wechat_web_devtools#5]
目前看出来的状况是链接不上网络，求大神解决呀

QQ:571618587

**Comment by jerry79** [comment]
同样的问题，我已经问过了，目前无解

**Comment by longwenfei** [comment]
16.04 同样问题。 提示70502904.debug.open.weixin.qq.com page isn't working .  didn't send any data.
作者是不是绑定了自己的QQ来做的？

**Comment by yuan1994** [comment]
不是，这个不是我的QQ，我的没问题，可能是系统的原因，微信故意不让我们在Linux系统上用的吧，上面那个应该是某个调试页面，被微信官方该关了，前面的那个id应该是个随机数，我在Ubuntu 14.04上只能勉强使用了

**Comment by longwenfei** [comment]
最后我还是使用VirtualBox 虚拟32位的win7系统。ubuntu安装samba，在win7系统中安装官方的程序，然后地址是使用远程ubuntu的地址即可调试了。ubuntu下进行代码编辑，官方的工具只进行调试。一切完美。

**Comment by jerry79** [comment]
@longwenfei 这个方法不错，我一开始用虚拟机本身的共享文件夹功能，官方工具一打开共享文件夹下面的目录就自动退出，现在按照你说的用samba就没问题。谢谢共享解决方法。

**Comment by yuan1994** [comment]
已更新，感谢大家的支持，因做毕设忙得没心情更新了，耽误大家了，很抱歉
