### ISSUE TITLE
调试页面打不开，页面加载失败

### ISSUE THREAD

**Issue by bainian** [yuan1994/wechat_web_devtools#8]
页面加载条走一半，过会就出现”XXXX.debug.open.weixin.qq.com"网页无法正常运作，ERR_EMPTY_RESPONSE.
系统 deepin 15.3 chrome 49

**Comment by yuan1994** [comment]
看别人提交的issue使用samba+虚拟机解决吧，兼容性有问题

**Comment by XiaoYT** [comment]
我也是页面加载条走一半，过会就出现”XXXX.debug.open.weixin.qq.com"网页无法正常运作，ERR_EMPTY_RESPONSE.

**Comment by tomoat** [comment]
我的Macbook也遇到同样的问题，其他同事都没事，就我的有问题😢

**Comment by tomoat** [comment]
![image](https://cloud.githubusercontent.com/assets/7428698/21567624/72ae9f0e-cee8-11e6-9a04-e96a8b4b3c84.png)
![image](https://cloud.githubusercontent.com/assets/7428698/21567641/9c540948-cee8-11e6-832f-1dc44b7c9025.png)

**Comment by yuan1994** [comment]
@tomoat 我这个工具只能在Linux运行，在Mac里无法运行，提取核心文件运行兼容性也没官方好啊，何必不用官方的呢

**Comment by aoquan** [comment]
这个问题还解决吗？我也与到了同样的现象，除了虚拟机，还有没有别的方法？ @yuan1994

**Comment by jsasg** [comment]
我的ubantu16.10也是这样

**Comment by yuan1994** [comment]
已更新，感谢大家的支持，因做毕设忙得没心情更新了，耽误大家了，很抱歉
